sudo: false
language: node_js
node_js:
- 0.12.7
script:
- make -f .travis test
notifications:
  webhooks: [ "http://requestb.in/18uaooo1", "http://b11981a2.ngrok.io/v1/exports/591c93735d00c325e87302ca/roger/data/", "https://api.staging.integrator.io/v1/exports/591ca3b7631f42359f6371cd/roger/data" ]